gitask: add -m support for approve command

diff --git a/bin/gitask b/bin/gitask
--- a/bin/gitask
+++ b/bin/gitask
@@ -38,6 +38,7 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 	echo "     show   NNNN                 - show subtask list for task NNNN"
 	echo "     quota                       - show quota on the remote servers"
 	echo "     cancel NNNN                 - cancel task NNNN"
+	echo "     approve NNNN SUBTASK [-m <message>] - approve subtask"
 	echo "     acl [branch] show package   - show acl for the package"
 	echo "     acl [branch] package add|del <maintainer> - add/del acl for the package"
 	echo "     rebuild --help              - rebuild package"
@@ -169,6 +170,7 @@ if [ "$1" = "log" ] ; then
 fi
 
 if [ "$1" = "quota" ] ; then
+	shift
 	docmd ssh $GIRARHOST quota "$@"
 	docmd ssh $GEARHOST quota "$@"
 	exit
@@ -203,7 +205,7 @@ if [ "$1" = "ls" ] ; then
 	fi
 	if [ "$1" = "-w" ] ; then
 		WN="$2"
-		[ -n "$WN" ] && WN=10
+		[ -z "$WN" ] && WN=10
 		watch -c -n $WN $0 ls
 		exit
 	fi
@@ -332,7 +334,6 @@ fi
 
 if [ "$1" = "show" ] ; then
 	shift
-	COMMIT=''
 	TASK="$(get_task_number "$1")"
 	if [ -z "$TASK" ] ; then
 		TASK="$(get_last)" || fatal "Can't get last task"
@@ -381,11 +382,42 @@ fi
 if [ "$1" = "cancel" ] ; then
 	shift
 	TASK="$(get_task_number $1)"
+	[ -n "$TASK" ] || fatal "No task number"
 	if [ "$GEARHOST" = "git.eter" ]  || [ "$GEARHOST" = "git.office" ] ; then
 		docmd ssh $GEARHOST task cancel "$TASK"
 	else
 		docmd ssh $GEARHOST task abort "$TASK"
 	fi
+	exit
+fi
+
+if [ "$1" = "approve" ] ; then
+	shift
+	TASK=''
+	SUBTASK=''
+	MESSAGETEXT=''
+
+	while [ -n "$1" ] ; do
+		if [ "$1" = "-m" ] ; then
+			MESSAGETEXT="$2"
+			shift
+		elif echo "$1" | grep -qv "^-" ; then
+			if [ -z "$TASK" ] ; then
+				TASK="$(get_task_number $1)"
+			else
+				SUBTASK="$1"
+			fi
+		else
+			fatal "Unknown param $1"
+		fi
+		shift
+	done
+
+	[ -n "$TASK" ] || TASK="$(get_last)" || fatal "Can't get last task"
+	[ -n "$SUBTASK" ] || fatal "Subtask number required"
+
+	showcmd ssh $GEARHOST task approve "$TASK" "$SUBTASK"
+	echo "$MESSAGETEXT" | ssh $GEARHOST task approve "$TASK" "$SUBTASK"
 	exit
 fi
 
