rpmgs: fatal on failed git merge in update_master_branch_to

diff --git a/bin/rpmgs b/bin/rpmgs
--- a/bin/rpmgs
+++ b/bin/rpmgs
@@ -412,9 +412,9 @@ update_master_branch_to()
 	[ -n "$tag" ] || fatal "Can't find tag for $GSSETVERSION version"
 	if [ -d "$(get_root_git_dir)/.gear/tags" ] ; then
 		info "Using 'ours' merge strategy for .gear/tags-based package"
-		docmd git merge -s ours $tag
+		docmd git merge -s ours $tag || fatal "Failed to merge tag $tag (ours strategy)"
 	else
-		docmd git merge $tag
+		docmd git merge $tag || fatal "Failed to merge tag $tag. Try 'git merge --allow-unrelated-histories $tag' manually."
 	fi
 
 	# TODO: it is more clean detect that dir
